biomarkers_list <- rbind.data.frame(c('SPARC', 'acidic', 'CG6378', 'fat body marker'),
                              c('acj6', 'acj6', 'CG9151', 'PN marker'),
                              c('alrm', 'alrm', 'CG11910', 'astrocyte marker'),
                              c('CG34367', 'CG34367', 'CG34367', 'astrocyte marker'),
                              c('CG4797', 'CG4797', 'CG4797', 'surface glia marker'),
                              c('CG8177', 'CG8177', 'CG8177', 'surface glia marker'),
                              c('ct', 'cut', 'CG11387', 'PN marker'),
                              c('Dop1R2', 'Dop1R2', 'CG18741', 'KC marker'),
                              c('elav', 'elav', 'CG4262', 'neuronal marker'),
                              c('ey', 'eyeless', 'CG1464', 'KC marker'),
                              c('Fas2', 'Fas2', 'CG3665', 'KC marker'),
                              c('kn', 'kn', 'CG10197', 'dendrite morphology marker'),
                              c('ImpL2', 'ImpL2', 'CG15009', 'surface glia marker'),
                              c('Indy', 'Indy', 'CG3979', 'fat body marker'),
                              c('Lim1', 'Lim1', 'CG11354', 'vPN marker'),
                              c('lncRNA:CR34335', 'MRE16', 'lncRNA:CR34335', 'glial marker'),
                              c('MtnA', 'MtnA', 'CG9470', 'fat body marker'),
                              c('nrv2', 'nrv2', 'CG9261', 'glial marker'),
                              c('nSyb', 'nSyb', 'CG17248', 'neuronal marker'),
                              c('pdgy', 'pdgy', 'CG9009', 'fat body marker'),
                              c('repo', 'repo', 'CG31240', 'glial marker'),
                              c('lncRNA:roX1', 'lncRNA:roX1', 'CR32777', 'male marker'),
                              # c('SLCs', 'glial marker'),
                              c('sNPF', 'sNPF', 'CG13968', 'PN marker'),
                              c('SPARC', 'SPARC', 'CG6378', 'fat body marker'),
                              c('SPARC', 'Secreted protein', 'CG6378', 'fat body marker'),
                              c('Tk', 'Tk', 'CG14734', 'IPN marker'),
                              c('Tret1-1', 'Tret1-1', 'CG30035', 'surface glia marker'),
                              c('trio', 'trio', 'CG18214', 'KC marker'),
                              # c('V-type', 'surface glia marker'),
                              c('vvl', 'vvl', 'CG10037', 'ensheathing glia marker'),
                              c('wun2', 'wun2', 'CG8805', 'astrocyte marker'))

colnames(biomarkers_list) <- c('gene name', 'other name', 'geneID', 'marker')

table(biomarkers_list[,4])

saveRDS(biomarkers_list, "/t1-data/project/sims-lab/lmorrill/robjects/lightning/biomarkers_list.RDS")

neurotransmitters_list <- c(c('Vmat', 'Monoamines'),
                            c('Frq1', 'Histamine'),
                            c('CG43795', 'Histamine'),
                            c('Lmx1a', 'Histamine'),
                            c('otp', 'Histamine'),
                            c('', 'Tyramine'),
                            c('Tdc2', 'Octopamine'),
                            c('Tbh', 'Octopamine'),
                            c('beat-Ib', 'Dopamine'),
                            c('beat-Ic', 'Dopamine'),
                            c('PDGF', 'Dopamine'),
                            c('VEGF', 'Dopamine'),
                            c('Pvf3', 'Dopamine'),
                            c('kek1', 'Dopamine'),
                            c('Toll-6', 'Dopamine'),
                            c('mirr', 'Dopamine'),
                            c('5-HT1A', 'Serotonin'),
                            c('JhI-21', 'Serotonin'),
                            c('vvl', 'Serotonin'),
                            c('ey', 'Serotonin'),
                            c('Lim3', 'Serotonin'),
                            c('5-HT', 'Serotonin'),
                            c('fru', 'Serotonin'))
