
rule all:
    input:
        expand("/home/l/lmorrill/projects/lighting/data/robjects/KB-dmel649ChrimsonV2/clustering_nPCs/{nPC}.RDS", nPC=[x for x in range(10,40)])

rule run_script:
    input:
       "ABOUT" 
    output:
        "/home/l/lmorrill/projects/lighting/data/robjects/KB-dmel649ChrimsonV2/clustering_nPCs/{nPC}.RDS"
    log:
        "logs/log_compute_clusters_PCs_resolution_nPC{nPC}"
    shell:
        "/ceph/package/c7/R-base/4.2.0/bin/Rscript compute_clusters_PCs_resolution.R --nPCs {wildcards.nPC}"

